create table usuario (
       id bigint generated by default as identity,
        password varchar(255),
        name varchar(255),
        login varchar(255),
        unique (login),
        primary key (id)
    )