create table role (
       id bigint generated by default as identity,
        name varchar(255),
        primary key (id)
);

create table user_role (
       usuario_id integer not null,
        role_id bigint not null,
        foreign key (role_id) references role(id),
        foreign key (usuario_id) references usuario(id)
);