create table student_level (
       id bigint generated by default as identity,
       usuario_id bigint not null,
       level_id integer not null,
       foreign key (usuario_id) references usuario(id),
       foreign key (level_id) references level(id),
       unique(usuario_id, level_id),
       primary key (id)
);
