create table page_book (
       id integer generated by default as identity,
       book_id integer not null,
       chapter integer not null,
       page_index bigint not null,
       content varchar,
       foreign key (book_id) references book(id)
);